print('hello git e vscode')
print('hello git e vscode')
print('hello git e vscode')
print('hello git e vscode')
print('hello git e vscode')
print('hello git e vscode')
print('hello git e vscode')
print('teste com visual code')